name: "Unittest"

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  Unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: unittest
        run: |
          python3 -m unittest discover tests
